name: Download Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-docker@v1
    - name: Download Docker Image
      run: docker pull syncthing/syncthing
